GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImVtYWlsIjoiUmFlbmFsQGdtYWlsLmNvbSIsImlhdCI6MTcwMjYyNzcyMiwiZXhwIjoxNzAyNjI3NzM3fQ.H4EKjXBsKjzEtUA6t9scyVJWoW_nF32KW0z4FUxeFrY

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "name" : "Raenal",
    "email": "Raenal@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "Raenal@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3000/token

###
DELETE http://localhost:5000/logout

###

